openapi: 3.0.3
info:
  title: Brutus
  description: |-
    Todo
  version: 1.0.11

paths:
  /doc/relSearch:
    post:
      tags:
        - doc
      summary: Search by relevance within a Doc
      operationId: relevanceSearch
      parameters:
        - name: DocId
          in: query
          description: DocId
          required: false
          explode: true
          schema:
            type: string
            default: 123
        - name: searchTerm
          in: query
          description: searchTerm
          required: false
          explode: true
          schema:
            type: string
            default: 123
      
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        '400':
          description: Invalid status value
          
  /doc/vecSearch:
    post:
      tags:
        - doc
      summary: Nearest neighbour vector search across parapgrapgs within a Doc
      operationId: vectorSearch
      parameters:
        - name: DocId
          in: query
          description: DocId
          required: false
          explode: true
          schema:
            type: string
            default: 123
        - name: seedVec
          in: query
          description: seedVec
          required: false
          explode: true
          schema:
            type:  array
            items: 
              type: number
              format: float
    
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        '400':
          description: Invalid status value
          
          
  /doc/hybridSearch:
    post:
      tags:
        - doc
      summary: Search by relevance and vector within a Doc
      operationId: hybridSearch
      parameters:
        - name: DocId
          in: query
          description: DocId
          required: false
          explode: true
          schema:
            type: string
            default: 123
        - name: seedVec
          in: query
          description: seedVec
          required: false
          explode: true
          schema:
            type:  array
            items: 
              type: number
              format: float
        - name: searchTerm
          in: query
          description: searchTerm
          required: false
          explode: true
          schema:
            type: string
            default: 123
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        '400':
          description: Invalid status value
          
          
  
  
components:
  schemas:
    Result:
      type: object
      properties:
        doc_id:
          type: integer
          format: int64
          example: 10
        petId:
          type: integer
          format: int64
          example: 198772
        quantity:
          type: integer
          format: int32
          example: 7
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
      xml:
        name: order
    