#!/bin/sh -xe

export AWS_ACCESS_KEY_ID=deltalake
export AWS_SECRET_ACCESS_KEY=weloverust
export AWS_ENDPOINT=http://localhost:4566
export AWS_ALLOW_HTTP=true
export BRUTUS_DOCUMENTS_URL=s3://brutus-data
export RUST_LOG=${RUST_LOG:-info}

exec catflap -- cargo watch -x run
