openapi: 3.0.3
info:
  title: Brutus
  description: |-
    Todo
  version: 1.0.11
servers:
  - url: /api/v1
    description: Development v1 endpoint

paths:
  /search/{docId}/relevance:
    post:
      tags:
        - doc
      summary: Search by relevance within a Doc
      parameters:
        - name: docId
          in: path
          example: 1106528470000
          description: ID of Doc to search
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelevanceSearchRequestBody'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        '400':
          description: Invalid status value
          
  /search/{docId}/vector:
    post:
      tags:
        - doc
      summary: Nearest neighbour vector search across parapgrapgs within a Doc
      operationId: vectorSearch
      parameters:
        - name: docId
          in: path
          description: ID of Doc to search
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VectorSearchRequestBody'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        '400':
          description: Invalid status value
          
          
  /search/{docId}/hybrid:
    post:
      tags:
        - doc
      summary: Search by relevance and vector within a Doc
      operationId: hybridSearch
      parameters:
        - name: docId
          in: path
          description: ID of Doc to search
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HybridSearchRequestBody'

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        '400':
          description: Invalid status value
          
          
components:
  schemas:
    HybridSearchRequestBody:
      type: object
      properties:
       query:
         type: string
       vector:
          type:  array
          items: 
            type: number
            format: float
    RelevanceSearchRequestBody:
      type: object
      properties:
       query:
         type: string
         example: chinchilla coats
    VectorSearchRequestBody:
      type: object
      properties:
       query:
          type:  array
          items: 
            type: number
            format: float
    Result:
      type: object
      properties:
        doc_id:
          type: integer
          format: int64
        score:
          type: number
          format: float
        text:
          type: string 
